name = "KenyaCoV"
uuid = "8af968fe-5b4e-4282-bf9e-761c92162993"
authors = ["Rabia Aziza <Rabia.Aziza@warwick.ac.uk>","Samuel Brand <S.Brand@warwick.ac.uk>","John Ojal <JOjal@kemri-wellcome.org>"]
version = "2.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
